# Generated by Django 3.1.3 on 2021-02-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=20)),
                ('team_log', models.CharField(default='no logo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_play', models.PositiveIntegerField(default=0, max_length=10)),
                ('win', models.PositiveIntegerField(default=0, max_length=10)),
                ('loss', models.PositiveIntegerField(default=0, max_length=10)),
                ('goal_scored', models.PositiveIntegerField(default=0, max_length=10)),
                ('goal_concede', models.PositiveIntegerField(default=0, max_length=10)),
                ('points', models.PositiveIntegerField(default=0, max_length=10)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resulttable.team')),
            ],
        ),
    ]
